extend type Category {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Category", purpose: IMPLICIT_KEY_FIELD)
}
extend type Comment {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Comment", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Comment`.`author`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  authorId: UUID! @fdc_generated(from: "Comment.author", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Comment`.`report`. It must match the value of `Report`.`id`. See `@ref` for how to customize it.
  """
  reportId: UUID! @fdc_generated(from: "Comment.report", purpose: IMPLICIT_REF_FIELD)
}
extend type Report {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Report", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Report`.`category`. It must match the value of `Category`.`id`. See `@ref` for how to customize it.
  """
  categoryId: UUID @fdc_generated(from: "Report.category", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Report`.`reporter`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  reporterId: UUID! @fdc_generated(from: "Report.reporter", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
extend type Vote {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Vote", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Vote`.`report`. It must match the value of `Report`.`id`. See `@ref` for how to customize it.
  """
  reportId: UUID! @fdc_generated(from: "Vote.report", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Vote`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Vote.user", purpose: IMPLICIT_REF_FIELD)
}
